apiVersion: apps/v1
kind: Deployment
metadata:
  name: symfony-app
  labels:
    app: symfony
spec:
  replicas: 2
  selector:
    matchLabels:
      app: symfony
  template:
    metadata:
      labels:
        app: symfony
    spec:
      containers:
      - name: symfony-app
        image: your-dockerhub-username/symfony-app:latest
        ports:
        - containerPort: 80
        env:
        - name: APP_ENV
          value: prod
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: symfony-secrets
              key: database_url
